### ISSUE TITLE
Same model, looking forward to any updates:)

### ISSUE THREAD

**Issue by jackhu9527** [hagenest/thinkpad-l13-yoga-hackintosh#1]
Hi there,

So I've got my L13 Yoga very recently, and was thinking out running Hackintosh on this machine. Well after a few Google searches I found that it seems there's no way to do this currently. I still have an older T460s which has Big Sur installed and works like a charm.

L13 Yoga isn't a best seller so I don't expect there will be tons of dev support, instead just want to stay hopeful, in case someone can figure things out someday. With the introduction of Apple's self-made silicon chip, the good old days of Hackintosh may soon be gone, but at least we have had good memories.

**Comment by hagenest** [comment]
I got it to work thanks to a tip in #2. I added my new EFI to the repo

**Comment by jackhu9527** [comment]
> 
> 
> I got it to work thanks to a tip in #2. I added my new EFI to the repo

Thanks, and I've just tried the new EFI on my laptop. Big Sur installation was successful, wow! Besides that, many of the hardware wasn't recognized or doesn't work: 
Keyboard and Trackpad
TouchScreen
Ethernet &Wifi  both notworking
Audio&Microphone
Camera
___________________________________
By the way, do you also have Windows 10 installed on the same machine and same ssd? I almost always have trouble booting into windows with OC EFI. 

Hope you guys can fix some(or all) of the issues. Have a nice day.:)

**Comment by hagenest** [comment]
For Wifi you have to add your SSID and password to the info.plist file in the itlwm.kext. If you have internet you can just install the app Heliport to manage your WiFi through a GUI.

Keyboard and Trackpad are working perfectly for me, I don't know what's the issue here. 🤔 
The camera will most likely never work, but I'll try to fix sound and touchscreen, when I have the time. 

Edit: Oh and I didn't try dual booting yet, but I'll probably try to install Linux next to macOS, I don't know if that helps with Windows though.

**Comment by jackhu9527** [comment]
Thanks for the swift response. I spent a few extra hours yesterday and today, and I've been able to get a few more things to work:
Built-in speaker and Microphone. Only thing I changed is the ALC Layout id, from originally 11 to 15.
Built-in Ethernet. By installing the Intel Mausi kext.
Built-in Intel wifi. By installing the intel wifi kext.
Hope this is helpful.

I know it may sounds weird and different from your experience, but the keyboard and trackpad, touchpad still don't work. I haven't changed anything in the EFI folder except for the ones I mentioned above.
It would be great if you can get the camera and the touch screen work, but it doesn't bother me as much as the keyword and trackpad. Hope someday someone can help me out with this.
