### ISSUE TITLE
Successful to boot macOS on X1C8

### ISSUE THREAD

**Issue by Xhichn** [hagenest/thinkpad-l13-yoga-hackintosh#2]
Hi, I had the same problem as yours stucking on `EXITBS:START` for a long time, but I managed to boot and install macOS on a X1 Carbon 8th Gen (i7 -10710U) with the EFI from this post, yet the reason is not clear: 

- https://github.com/daliansky/XiaoXinPro-13-hackintosh

Hope this info can help you :D

**Comment by hagenest** [comment]
Many thanks, I'll look into it :)

**Comment by hagenest** [comment]
So, I took their EFI and just tried it without changing a thing. It works! Or at least I'm getting into the installer. I don't have my LAN-Adapter with me right now, so I the next step will have to wait.
Thank you very very much :D
